export const FEATURE_LIST_REQUEST = 'FEATURE_LIST_REQUEST'
export const FEATURE_LIST_SUCCESS = 'FEATURE_LIST_SUCCESS'
export const FEATURE_LIST_FAIL = 'FEATURE_LIST_FAIL'

export const FEATURE_DETAILS_REQUEST = 'FEATURE_DETAILS_REQUEST'
export const FEATURE_DETAILS_SUCCESS = 'FEATURE_DETAILS_SUCCESS'
export const FEATURE_DETAILS_FAIL = 'FEATURE_DETAILS_FAIL'

export const FEATURE_DELETE_REQUEST = 'FEATURE_DELETE_REQUEST'
export const FEATURE_DELETE_SUCCESS = 'FEATURE_DELETE_SUCCESS'
export const FEATURE_DELETE_FAIL = 'FEATURE_DELETE_FAIL'

export const FEATURE_CREATE_REQUEST = 'FEATURE_CREATE_REQUEST'
export const FEATURE_CREATE_SUCCESS = 'FEATURE_CREATE_SUCCESS'
export const FEATURE_CREATE_FAIL = 'FEATURE_CREATE_FAIL'
export const FEATURE_CREATE_RESET = 'FEATURE_CREATE_RESET'

export const FEATURE_UPDATE_REQUEST = 'FEATURE_UPDATE_REQUEST'
export const FEATURE_UPDATE_SUCCESS = 'FEATURE_UPDATE_SUCCESS'
export const FEATURE_UPDATE_FAIL = 'FEATURE_UPDATE_FAIL'
export const FEATURE_UPDATE_RESET = 'FEATURE_UPDATE_RESET'
